tachyons-css/tachyons

- docs/typography/font-family/index.html
> Fix font family copy typo

- docs/typography/vertical-align/index.html
This feels like it should read as **affects**.
> I think this should be plural

- docs/layout/spacing/index.html
> Fix for docs/spacing

- README.md
> Added link to Tachyons slack channel.

- src/_heights.css
This fixes some inconsistent class names in height breakpoints.
> Fix heights at ns breakpoint

- readme.md
+ tachyons-powered Wordpress theme
+ my comics website
> Updating list of tachyons sites

- code-of-conduct.md
What do people think of this? Wanted to put it up for public review. If something needs to be added or modified please let me know! It is important to me that this is an inclusive community.
> Add code of conduct.

- readme.md
> Adding my bits to the README

- src/_skins.css
Really, just cosmetical changes to the code.
> Lowercase hex colors

- readme.md
> Adds my site (colepeters.com) to the list of sites using Tachyons

- readme.md
> Add funponent to Websites that Use Tachyons

- readme.md
Just a quick update to match the new npm package.
> docs: update version number and cdn link in readme.md

- css/tachyons.css
Only changes are from upper to lower case letters, but still worth updating for consistency IMO.
> chore: update compiled css for v4.1.1

- readme.md
Ohai! Recently redid my blog with Tachyons, so I added it to the list.
Thanks! 🍻
> Add my blog to the site list

- css/tachyons.css
- package.json
In order to ensure that the build doesn't cause
a bug in the .grow selector I've temporarily removed
trimTrailingZeros.
This will be added back once I get a fix in to
the perfectionist library.
***
Related ben-eb/perfectionist#42
Closes #261
> Fix the build and bump to the latest cli version

- readme.md
Recently refreshed the placeholder view on my personal site (https://github.com/talbs/talbs.me). Was super easy using Tachyons - thanks again for the awesome utilities, gang. 😄
> Add talbs.me to Site List

- readme.md
Loved working with Tachyons. After tinkering with various css framework, from big to the minimal, tachyons has been my favorite to work with. Thanks mrmrs.
> Adding https://www.hiaida.com to list of sites

- readme.md
DevDayAR is a conference that will take place this Saturday on Buenos Aires :sunglasses:
> Add DevDayAR to "Websites that Use Tachyons"

- src/_border-colors.css
> Add moon-gray to border colors

- src/_widths.css
Some values were missing in the comments.
> Update widths documentation comment

- readme.md
We're very proud to use Tachyons on our newly released https://fontawesome.com. Thanks for the great resource and keep up the great work, gang!
> Adding fontawesome.com to Site List

- package.json
Fixed in accordance with https://github.com/jupyterlab/jupyterlab/pull/791/commits/e12ac9a8217e034387f17ec286ab0bddc8c199fc as npm start failed.
> Fix watch statements on Windows

- sites.md
> Adds Hatch Loyalty to list of sites using Tachyons

- readme.md
Here's a quick PR that updates the latest version number in the readme to match the actual latest version number.
> Update readme version number

- sites.md
First big project of mine with tachyons, love the library :)
> add tylerdeitz.com to sites.md

- sites.md
Adding Tribe Kampala to list of tachyons sites.
> Add Tribe Kampala to list of Tachyons sites

- sites.md
> Add starklabs.io

- sites.md
> add Pylon.design to list of sites

- docs/layout/debug.md
- docs/pages/docs/layout/debug.js
Port of the debug docs page from the 4.9.1 documentation site.
> Add Debug Docs 

- docs/layout/debug-grid.md
- docs/pages/docs/layout/debug-grid.js
Port debug grid docs from 4.9.1.
> add debug grid docs

- docs/package-lock.json
- docs/pages/docs/themes/hovers.js
- docs/themes/hovers.md
- docs/ui/data.json
Note: The "Reveal Children on Hover" example is not displaying correctly. I copied and pasted the example from the current docs. Does it need to be changed in some manner for this version?
> Port hover documentation

- docs/pages/docs/layout/flexbox.js
The markdown file was there already, just making a page for it.
> Add flexbox docs page

- docs/pages/docs/layout/floats.js
The markdown document was already there. Just adding the page.
> Add floats page

- docs/layout/clearfix.md
- docs/pages/docs/layout/clearfix.js
Port of clearfix docs from 4.9.1.
> Add clearfix docs

- docs/layout/display.md
- docs/pages/docs/layout/display.js
> Add display docs

- docs/layout/widths.md
- docs/pages/docs/layout/widths.js
Port of widths docs from 4.9.1.
> Add widths docs

- docs/layout/max-widths.md
- docs/pages/docs/layout/max-widths.js
> Add max-widths docs

- docs/layout/position.md
- docs/pages/docs/layout/position.js
> Add position docs

- docs/pages/xray.js
One notable difference between this and the current version is that this has the Tachyons header, which I think is okay but I thought you should know.
Also, the Carbon ad requires `dangerouslySetInnerHTML` 🤢 and I used a touch of Next's styled JSX on line `133`.
> Add Xray Page

- docs/pages/gallery.js
> Add Gallery Page

- docs/package-lock.json
- docs/pages/docs/typography/font-style.js
- docs/pages/docs/typography/font-weight.js
- docs/pages/docs/typography/line-height.js
- docs/pages/docs/typography/measure.js
- docs/pages/docs/typography/text-align.js
- docs/pages/docs/typography/text-decoration.js
- docs/pages/docs/typography/text-transform.js
- docs/pages/docs/typography/tracking.js
- docs/pages/docs/typography/vertical-align.js
- docs/pages/docs/typography/white-space.js
- docs/typography/font-style.md
- docs/typography/font-weight.md
- docs/typography/line-height.md
- docs/typography/measure.md
- docs/typography/text-align.md
- docs/typography/text-decoration.md
- docs/typography/text-transform.md
- docs/typography/tracking.md
- docs/typography/vertical-align.md
- docs/typography/white-space.md
- docs/ui/MeasureHero.js
- docs/ui/data.json
Note: Can someone please check over my port of the measure.md page. I don't trust my design sense enough to be sure everything looks how it should. (Especially since there are slight expected variations between old and new.)
> Structure for typography doc pages and content for the measure.md

- sites.md
We use tachyons-custom to design everything, and really enjoy it - thanks!
> Add Observable to sites

- src/_spacing.css
Fixes #489 
Branched off of v5, will be added to #455 on merge
> Adds vertical margin auto classes

- readme.md
Add my new website [BitMidi](https://bitmidi.com) to the readme. It uses Tachyons!
> Add BitMidi to the readme

- sites.md
This entry was missing an `*`.
> Fix list rendering in sites.md
